services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 1g
    ports:
      - 5678:5678
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DATABASE}
      - DB_POSTGRESDB_HOST=${DB_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../../n8n_data:/home/node/.n8n
    networks:
      - sharednetwork

networks:
  sharednetwork:
    external: true